name: Smoke Suite Web Run
on:
  push:
    branches: [ main ]
  workflow_dispatch: # This allows you to click a "Run" button manually

jobs:
  test:
    runs-on: ubuntu-latest # This runs it on a GitHub cloud server
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest playwright pytest-playwright pytest-html
          playwright install --with-deps chromium

      - name: Run Smoke Suite
        run: pytest -m smoke --html=report.html --self-contained-html

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-report
          path: report.html